### ISSUE TITLE
matrix44.create_look_at dtype not understood

### ISSUE THREAD

**Issue by Korijn** [adamlwgriffiths/Pyrr#56]
It is a little surprising to me that this works:

```
>>> import pyrr
>>> pyrr.matrix44.create_perspective_projection(45.0, 4.0/3.0, 0.1, 1000.0, dtype='f4')
array([[ 1.81066012,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.41421366,  0.        ,  0.        ],
       [ 0.        ,  0.        , -1.00020003, -1.        ],
       [ 0.        ,  0.        , -0.20002   ,  0.        ]], dtype=float32)
```

But that this does not:

```
>>> pyrr.matrix44.create_look_at([10, 10, 10], [0, 0, 0], [0, 1, 0], dtype='f4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ssd2/miniconda3/envs/radiant/lib/python3.6/site-packages/pyrr/utils.py", line 25, in wrapper
    return fn(*args, **kwargs)
  File "/media/ssd2/miniconda3/envs/radiant/lib/python3.6/site-packages/pyrr/matrix44.py", line 473, in create_look_at
    ), dtype=dtype)
TypeError: data type not understood
```

Is that a bug?

**Comment by cprogrammer1994** [comment]
found the problem:

all the functions with a decorator as follows are broken:

```python
@all_parameters_as_numpy_arrays
def foobar(*parameters, dtype=None):
```

`dtype` will be converted to a numpy array (`dtype <class 'numpy.ndarray'> f4`)

@adamlwgriffiths should we patch the `all_parameters_as_numpy_arrays` to skip `dtype` or is there a better solution?

**Comment by cprogrammer1994** [comment]
quaternion lerp & slerp may be affected too. (those have a parameter `t` that should be a scalar not an array)

**Comment by adamlwgriffiths** [comment]
Damn. I hadn't noticed.
We should add tests to catch this.

One solution is to remove `all_parameters_as_numpy_arrays` and replace with `parameters_as_numpy_arrays`, which takes an argument of the parameter names to convert.

```
@parameters_as_numpy_arrays('m1', 'm2')
def func(m1, m2, dtype=None):
 pass
```

**Comment by cprogrammer1994** [comment]
I will change the functions to use explicit calls

**Comment by Korijn** [comment]
Why use `np.array` instead of `np.asarray`, by the way?

**Comment by cprogrammer1994** [comment]
good to know thanks

**Comment by cprogrammer1994** [comment]
@Korijn please confirm if the problem is solved.
Thanks for pointing out the issue!

**Comment by Korijn** [comment]
LGTM! I'll test it later today. Is it on pypi or should I check out a git rev?

**Comment by cprogrammer1994** [comment]
pypi

**Comment by Korijn** [comment]
```python
In [7]: pyrr.matrix44.create_look_at([10, 10, 10], [0, 0, 0], [0, 1, 0], dtype='f4')
Out[7]: 
array([[  0.70710677,  -0.40824831,   0.57735026,   0.        ],
       [  0.        ,   0.81649661,   0.57735026,   0.        ],
       [ -0.70710677,  -0.40824831,   0.57735026,   0.        ],
       [ -0.        ,  -0.        , -17.32050896,   1.        ]], dtype=float32)
```

Fixed! Thanks guys.
